[package]
name = "hello-particles"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
particle-tools = { path = "../lib/particle-tools" }
serde_json = "1"
tokimu = { path = "../../crates/tokimu", features = ["platform", "render"] }
