[package]
name = "hello-doom-spatial-query-portable"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
tokimu-core = { path = "../../../../crates/tokimu-core" }
tokimu-spatial-query-study = { path = "../../../lib/tokimu-spatial-query-study" }

[dev-dependencies]
wasm-bindgen-test = "=0.3.76"
