/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmobservationshellsession_free: (a: number, b: number) => void;
export const __wbg_wasmruntimeobservationsession_free: (a: number, b: number) => void;
export const wasmobservationshellsession_advance_animation_fixed_step: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_animation_catalog_json: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_apply_json: (a: number, b: number) => [number, number, number, number];
export const wasmobservationshellsession_command_catalog_json: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_enqueue_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmobservationshellsession_execute_json: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmobservationshellsession_latest_observation_diff_json: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_new: () => [number, number, number];
export const wasmobservationshellsession_observation_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmobservationshellsession_playback_command_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmobservationshellsession_playback_json: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_presentation_json: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_ratatui_append_text: (a: number, b: number, c: number) => void;
export const wasmobservationshellsession_ratatui_backspace: (a: number) => void;
export const wasmobservationshellsession_ratatui_clear_prompt: (a: number) => void;
export const wasmobservationshellsession_ratatui_frame_height: (a: number) => number;
export const wasmobservationshellsession_ratatui_frame_rgba: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmobservationshellsession_ratatui_frame_width: (a: number) => number;
export const wasmobservationshellsession_ratatui_history_down: (a: number) => void;
export const wasmobservationshellsession_ratatui_history_up: (a: number) => void;
export const wasmobservationshellsession_ratatui_scroll_by: (a: number, b: number) => void;
export const wasmobservationshellsession_ratatui_submit: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_select_arm_presentation_json: (a: number) => [number, number, number, number];
export const wasmobservationshellsession_ui_snapshot_json: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmruntimeobservationsession_advance_animation_fixed_step: (a: number) => [number, number, number, number];
export const wasmruntimeobservationsession_animation_catalog_json: (a: number) => [number, number, number, number];
export const wasmruntimeobservationsession_apply_json: (a: number, b: number) => [number, number, number, number];
export const wasmruntimeobservationsession_enqueue_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmruntimeobservationsession_latest_observation_diff_json: (a: number) => [number, number, number, number];
export const wasmruntimeobservationsession_new: () => [number, number, number];
export const wasmruntimeobservationsession_observation_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmruntimeobservationsession_playback_command_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmruntimeobservationsession_playback_json: (a: number) => [number, number, number, number];
export const wasmruntimeobservationsession_presentation_json: (a: number) => [number, number, number, number];
export const wasmruntimeobservationsession_select_arm_presentation_json: (a: number) => [number, number, number, number];
export const wasmruntimeobservationsession_ui_snapshot_json: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
