//! Deliberately narrow WAVE fixture adaptation for audio corpus evidence.
//!
//! This module accepts only generated RIFF/WAVE PCM16 little-endian data. It
//! proves that a provider-specific byte source can stop at `PcmAudioWindow`
//! before analysis. It is not a media decoder, file playback API, or public
//! audio capability.

use thiserror::Error;

use crate::{PcmAnalysisError, PcmAudioWindow, PcmFixture, MAX_PCM_CHANNELS, MAX_PCM_FRAMES};

const RIFF_HEADER_BYTES: usize = 12;
const CHUNK_HEADER_BYTES: usize = 8;
const PCM_FORMAT_TAG: u16 = 1;
const PCM16_BITS_PER_SAMPLE: u16 = 16;
const PCM16_BYTES_PER_SAMPLE: usize = 2;
const MAX_WAV_FIXTURE_BYTES: usize = 16 * 1024;

/// Decodes a bounded PCM16 little-endian RIFF/WAVE fixture into normalized PCM.
///
/// Unknown chunks are skipped according to RIFF alignment rules so fixtures can
/// include benign metadata without making it part of the analysis contract.
pub fn decode_pcm16_wav(bytes: &[u8]) -> Result<PcmAudioWindow, WavFixtureError> {
    if bytes.len() > MAX_WAV_FIXTURE_BYTES {
        return Err(WavFixtureError::TooManyBytes {
            bytes: bytes.len(),
            maximum: MAX_WAV_FIXTURE_BYTES,
        });
    }
    if bytes.len() < RIFF_HEADER_BYTES {
        return Err(WavFixtureError::TruncatedRiffHeader);
    }
    if &bytes[0..4] != b"RIFF" || &bytes[8..12] != b"WAVE" {
        return Err(WavFixtureError::InvalidRiffWaveSignature);
    }

    let declared_size = read_u32(bytes, 4)? as usize;
    if declared_size.checked_add(8) != Some(bytes.len()) {
        return Err(WavFixtureError::RiffLengthMismatch {
            declared_size,
            actual_bytes: bytes.len(),
        });
    }

    let mut offset = RIFF_HEADER_BYTES;
    let mut format = None;
    let mut data = None;
    while offset < bytes.len() {
        if bytes.len().saturating_sub(offset) < CHUNK_HEADER_BYTES {
            return Err(WavFixtureError::TruncatedChunkHeader { offset });
        }
        let chunk_id = [
            bytes[offset],
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
        ];
        let chunk_size = read_u32(bytes, offset + 4)? as usize;
        let data_start = offset + CHUNK_HEADER_BYTES;
        let data_end = data_start
            .checked_add(chunk_size)
            .filter(|end| *end <= bytes.len())
            .ok_or(WavFixtureError::TruncatedChunkData { offset, chunk_size })?;

        match &chunk_id {
            b"fmt " => format = Some(parse_format(&bytes[data_start..data_end])?),
            b"data" if data.is_none() => data = Some(&bytes[data_start..data_end]),
            _ => {}
        }

        offset = data_end + (chunk_size % 2);
        if offset > bytes.len() {
            return Err(WavFixtureError::TruncatedChunkPadding { offset });
        }
    }

    let format = format.ok_or(WavFixtureError::MissingFormatChunk)?;
    let data = data.ok_or(WavFixtureError::MissingDataChunk)?;
    if data.len() % format.block_align != 0 {
        return Err(WavFixtureError::IncompleteFrameData {
            bytes: data.len(),
            block_align: format.block_align,
        });
    }
    let frames = data.len() / format.block_align;
    if frames == 0 {
        return Err(WavFixtureError::EmptyDataChunk);
    }
    if frames > MAX_PCM_FRAMES {
        return Err(WavFixtureError::TooManyFrames {
            frames,
            maximum: MAX_PCM_FRAMES,
        });
    }

    let samples = data
        .chunks_exact(PCM16_BYTES_PER_SAMPLE)
        .map(|sample| i16::from_le_bytes([sample[0], sample[1]]) as f32 / 32_768.0)
        .collect();
    PcmAudioWindow::new(samples, format.sample_rate_hz, format.channels)
        .map_err(WavFixtureError::InvalidPcmWindow)
}

/// Encodes a deterministic PCM fixture as a minimal PCM16 RIFF/WAVE file.
///
/// The generated bytes are corpus input, not an interchange or export API.
pub fn encode_pcm16_wav_fixture(fixture: PcmFixture) -> Vec<u8> {
    let window = fixture.window();
    let data_bytes = window.interleaved_samples.len() * PCM16_BYTES_PER_SAMPLE;
    let riff_size = 4 + CHUNK_HEADER_BYTES + 16 + CHUNK_HEADER_BYTES + data_bytes;
    let block_align = u16::from(window.channels) * PCM16_BYTES_PER_SAMPLE as u16;
    let byte_rate = window.sample_rate_hz * u32::from(block_align);
    let mut bytes = Vec::with_capacity(RIFF_HEADER_BYTES + riff_size);
    bytes.extend_from_slice(b"RIFF");
    bytes.extend_from_slice(&(riff_size as u32).to_le_bytes());
    bytes.extend_from_slice(b"WAVEfmt ");
    bytes.extend_from_slice(&16_u32.to_le_bytes());
    bytes.extend_from_slice(&PCM_FORMAT_TAG.to_le_bytes());
    bytes.extend_from_slice(&u16::from(window.channels).to_le_bytes());
    bytes.extend_from_slice(&window.sample_rate_hz.to_le_bytes());
    bytes.extend_from_slice(&byte_rate.to_le_bytes());
    bytes.extend_from_slice(&block_align.to_le_bytes());
    bytes.extend_from_slice(&PCM16_BITS_PER_SAMPLE.to_le_bytes());
    bytes.extend_from_slice(b"data");
    bytes.extend_from_slice(&(data_bytes as u32).to_le_bytes());
    for sample in window.interleaved_samples {
        let pcm = (sample.clamp(-1.0, 1.0) * 32_767.0).round() as i16;
        bytes.extend_from_slice(&pcm.to_le_bytes());
    }
    bytes
}

#[derive(Clone, Copy, Debug)]
struct Pcm16Format {
    sample_rate_hz: u32,
    channels: u8,
    block_align: usize,
}

fn parse_format(bytes: &[u8]) -> Result<Pcm16Format, WavFixtureError> {
    if bytes.len() != 16 {
        return Err(WavFixtureError::UnsupportedFormatChunkLength { bytes: bytes.len() });
    }
    let format_tag = read_u16(bytes, 0)?;
    let raw_channels = read_u16(bytes, 2)?;
    let sample_rate_hz = read_u32(bytes, 4)?;
    let block_align = read_u16(bytes, 12)?;
    let bits_per_sample = read_u16(bytes, 14)?;
    if format_tag != PCM_FORMAT_TAG || bits_per_sample != PCM16_BITS_PER_SAMPLE {
        return Err(WavFixtureError::UnsupportedEncoding {
            format_tag,
            bits_per_sample,
        });
    }
    let channels =
        u8::try_from(raw_channels).map_err(|_| WavFixtureError::UnsupportedChannels {
            channels: raw_channels,
            maximum: MAX_PCM_CHANNELS,
        })?;
    if channels == 0 || channels > MAX_PCM_CHANNELS {
        return Err(WavFixtureError::UnsupportedChannels {
            channels: u16::from(channels),
            maximum: MAX_PCM_CHANNELS,
        });
    }
    let expected_block_align = usize::from(channels) * PCM16_BYTES_PER_SAMPLE;
    if usize::from(block_align) != expected_block_align {
        return Err(WavFixtureError::InvalidBlockAlign {
            block_align,
            expected: expected_block_align as u16,
        });
    }
    if sample_rate_hz == 0 {
        return Err(WavFixtureError::EmptySampleRate);
    }
    Ok(Pcm16Format {
        sample_rate_hz,
        channels,
        block_align: expected_block_align,
    })
}

fn read_u16(bytes: &[u8], offset: usize) -> Result<u16, WavFixtureError> {
    let end = offset + 2;
    let bytes = bytes
        .get(offset..end)
        .ok_or(WavFixtureError::TruncatedValue { offset })?;
    Ok(u16::from_le_bytes([bytes[0], bytes[1]]))
}

fn read_u32(bytes: &[u8], offset: usize) -> Result<u32, WavFixtureError> {
    let end = offset + 4;
    let bytes = bytes
        .get(offset..end)
        .ok_or(WavFixtureError::TruncatedValue { offset })?;
    Ok(u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]))
}

#[derive(Clone, Debug, Error, PartialEq)]
pub enum WavFixtureError {
    #[error("WAVE fixture contains {bytes} bytes; maximum is {maximum}")]
    TooManyBytes { bytes: usize, maximum: usize },
    #[error("WAVE fixture is missing the 12-byte RIFF header")]
    TruncatedRiffHeader,
    #[error("WAVE fixture must begin with a RIFF/WAVE signature")]
    InvalidRiffWaveSignature,
    #[error(
        "RIFF declared {declared_size} payload bytes but fixture contains {actual_bytes} bytes"
    )]
    RiffLengthMismatch {
        declared_size: usize,
        actual_bytes: usize,
    },
    #[error("WAVE chunk header is truncated at byte {offset}")]
    TruncatedChunkHeader { offset: usize },
    #[error("WAVE chunk at byte {offset} declares {chunk_size} bytes beyond the fixture")]
    TruncatedChunkData { offset: usize, chunk_size: usize },
    #[error("WAVE chunk padding extends beyond the fixture at byte {offset}")]
    TruncatedChunkPadding { offset: usize },
    #[error("WAVE value is truncated at byte {offset}")]
    TruncatedValue { offset: usize },
    #[error("WAVE fixture has no fmt chunk")]
    MissingFormatChunk,
    #[error("WAVE fixture has no data chunk")]
    MissingDataChunk,
    #[error("WAVE fmt chunk is {bytes} bytes; only canonical 16-byte PCM is admitted")]
    UnsupportedFormatChunkLength { bytes: usize },
    #[error("WAVE format tag {format_tag} with {bits_per_sample} bits is unsupported; only PCM16 is admitted")]
    UnsupportedEncoding {
        format_tag: u16,
        bits_per_sample: u16,
    },
    #[error("WAVE channels {channels} are unsupported; maximum is {maximum}")]
    UnsupportedChannels { channels: u16, maximum: u8 },
    #[error("WAVE block alignment {block_align} is invalid; expected {expected}")]
    InvalidBlockAlign { block_align: u16, expected: u16 },
    #[error("WAVE sample rate must be non-zero")]
    EmptySampleRate,
    #[error("WAVE data contains {bytes} bytes which does not align to {block_align}-byte frames")]
    IncompleteFrameData { bytes: usize, block_align: usize },
    #[error("WAVE data contains no PCM frames")]
    EmptyDataChunk,
    #[error("WAVE fixture has {frames} frames; maximum is {maximum}")]
    TooManyFrames { frames: usize, maximum: usize },
    #[error("WAVE fixture did not produce a valid PCM analysis window: {0}")]
    InvalidPcmWindow(#[from] PcmAnalysisError),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_pcm16_fixture_round_trips_into_analysis_input() {
        for fixture in PcmFixture::ALL {
            let source = fixture.window();
            let decoded = decode_pcm16_wav(&encode_pcm16_wav_fixture(fixture)).unwrap();
            assert_eq!(decoded.sample_rate_hz, source.sample_rate_hz);
            assert_eq!(decoded.channels, source.channels);
            assert_eq!(decoded.frame_count(), source.frame_count());
            for (actual, expected) in decoded
                .interleaved_samples
                .iter()
                .zip(source.interleaved_samples.iter())
            {
                assert!((actual - expected).abs() <= 1.0 / 32_767.0);
            }
        }
    }

    #[test]
    fn non_pcm16_encoding_is_rejected_before_analysis() {
        let mut bytes = encode_pcm16_wav_fixture(PcmFixture::Silence);
        bytes[20..22].copy_from_slice(&3_u16.to_le_bytes());
        assert!(matches!(
            decode_pcm16_wav(&bytes),
            Err(WavFixtureError::UnsupportedEncoding { format_tag: 3, .. })
        ));
    }

    #[test]
    fn malformed_riff_length_is_rejected_before_analysis() {
        let mut bytes = encode_pcm16_wav_fixture(PcmFixture::Silence);
        bytes[4..8].copy_from_slice(&0_u32.to_le_bytes());
        assert!(matches!(
            decode_pcm16_wav(&bytes),
            Err(WavFixtureError::RiffLengthMismatch { .. })
        ));
    }

    #[test]
    fn aligned_unknown_chunks_do_not_change_pcm_analysis_input() {
        let original = encode_pcm16_wav_fixture(PcmFixture::ToneAtBin8);
        let with_metadata = insert_unknown_chunk(&original, *b"JUNK", &[1, 2, 3]);

        let expected = decode_pcm16_wav(&original).unwrap();
        let actual = decode_pcm16_wav(&with_metadata).unwrap();
        assert_eq!(actual, expected);
    }

    fn insert_unknown_chunk(bytes: &[u8], id: [u8; 4], payload: &[u8]) -> Vec<u8> {
        let format_end = RIFF_HEADER_BYTES + CHUNK_HEADER_BYTES + 16;
        let mut result = Vec::with_capacity(bytes.len() + CHUNK_HEADER_BYTES + payload.len() + 1);
        result.extend_from_slice(&bytes[..format_end]);
        result.extend_from_slice(&id);
        result.extend_from_slice(&(payload.len() as u32).to_le_bytes());
        result.extend_from_slice(payload);
        if !payload.len().is_multiple_of(2) {
            result.push(0);
        }
        result.extend_from_slice(&bytes[format_end..]);
        let riff_size = (result.len() - 8) as u32;
        result[4..8].copy_from_slice(&riff_size.to_le_bytes());
        result
    }
}
